name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Log in to GitHub Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Build Docker image
    #   run: docker build . --tag ghcr.io/${{ github.repository }}:latest

    # - name: Push Docker image to GHCR
    #   run: docker push ghcr.io/${{ github.repository }}:latest

    - name: Inspect Schema Revisions
      run: |
        docker run --rm -v ${{ github.workspace }}:/src -w /src arigaio/atlas --url "${{ secrets.GA_DB_URI }}?search_path=public" migrate status --dir file://db/migrations

    - name: Run Migrations
      run: |
        docker run --rm -v ${{ github.workspace }}:/src -w /src \
          arigaio/atlas --env prod --url "${{ secrets.GA_DB_URI }}?search_path=public" migrate apply --dir file://db/migrations

    # - name: Deploy to Hetzner Server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HETZNER_HOST }}
    #     username: ${{ secrets.HETZNER_USER }}
    #     key: ${{ secrets.HETZNER_SSH_KEY }}
    #     script: |
    #       # Log in to GHCR on the server
    #       echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    #       # Pull the latest image from GHCR
    #       docker pull ghcr.io/${{ github.repository }}:latest

    #       # Stop and remove the old container if it exists
    #       docker stop portfolio-backend || true
    #       docker rm portfolio-backend || true

    #       # Run the new container from the new image
    #       docker run -d \
    #         --name portfolio-backend \
    #         -p 8080:8080 \
    #         -e DB_URL=${{ secrets.DB_URL }} \
    #         ghcr.io/${{ github.repository }}:latest

    #       echo "Deployment complete!"
